// /** @type {import('tailwindcss').Config} */
// export default {
//   content: [
//     "./index.html",
//     "./src/**/*.{js,ts,jsx,tsx}",
//   ],
//   theme: {
//     extend: {
//       colors: {
//         primary: {
//           50: 'var(--color-primary-50)',
//           100: 'var(--color-primary-100)',
//           200: 'var(--color-primary-200)',
//           300: 'var(--color-primary-300)',
//           400: 'var(--color-primary-400)',
//           500: 'var(--color-primary-500)',
//           600: 'var(--color-primary-600)',
//           700: 'var(--color-primary-700)',
//           800: 'var(--color-primary-800)',
//           900: 'var(--color-primary-900)',
//           950: 'var(--color-primary-950)',
//         },
//         secondary: {
//           50: 'var(--color-secondary-50)',
//           100: 'var(--color-secondary-100)',
//           200: 'var(--color-secondary-200)',
//           300: 'var(--color-secondary-300)',
//           400: 'var(--color-secondary-400)',
//           500: 'var(--color-secondary-500)',
//           600: 'var(--color-secondary-600)',
//           700: 'var(--color-secondary-700)',
//           800: 'var(--color-secondary-800)',
//           900: 'var(--color-secondary-900)',
//           950: 'var(--color-secondary-950)',
//         },
//         accent: {
//           50: 'var(--color-accent-50)',
//           100: 'var(--color-accent-100)',
//           200: 'var(--color-accent-200)',
//           300: 'var(--color-accent-300)',
//           400: 'var(--color-accent-400)',
//           500: 'var(--color-accent-500)',
//           600: 'var(--color-accent-600)',
//           700: 'var(--color-accent-700)',
//           800: 'var(--color-accent-800)',
//           900: 'var(--color-accent-900)',
//           950: 'var(--color-accent-950)',
//         },
//         success: {
//           50: 'var(--color-success-50)',
//           100: 'var(--color-success-100)',
//           200: 'var(--color-success-200)',
//           300: 'var(--color-success-300)',
//           400: 'var(--color-success-400)',
//           500: 'var(--color-success-500)',
//           600: 'var(--color-success-600)',
//           700: 'var(--color-success-700)',
//           800: 'var(--color-success-800)',
//           900: 'var(--color-success-900)',
//           950: 'var(--color-success-950)',
//         },
//         warning: {
//           50: 'var(--color-warning-50)',
//           100: 'var(--color-warning-100)',
//           200: 'var(--color-warning-200)',
//           300: 'var(--color-warning-300)',
//           400: 'var(--color-warning-400)',
//           500: 'var(--color-warning-500)',
//           600: 'var(--color-warning-600)',
//           700: 'var(--color-warning-700)',
//           800: 'var(--color-warning-800)',
//           900: 'var(--color-warning-900)',
//           950: 'var(--color-warning-950)',
//         },
//         error: {
//           50: 'var(--color-error-50)',
//           100: 'var(--color-error-100)',
//           200: 'var(--color-error-200)',
//           300: 'var(--color-error-300)',
//           400: 'var(--color-error-400)',
//           500: 'var(--color-error-500)',
//           600: 'var(--color-error-600)',
//           700: 'var(--color-error-700)',
//           800: 'var(--color-error-800)',
//           900: 'var(--color-error-900)',
//           950: 'var(--color-error-950)',
//         },
//       },
//       fontFamily: {
//         sans: ['var(--font-family-sans)'],
//         mono: ['var(--font-family-mono)'],
//         serif: ['var(--font-family-serif)'],
//       },
//       fontSize: {
//         xs: ['var(--text-xs)', { lineHeight: 'var(--leading-tight)' }],
//         sm: ['var(--text-sm)', { lineHeight: 'var(--leading-tight)' }],
//         base: ['var(--text-base)', { lineHeight: 'var(--leading-normal)' }],
//         lg: ['var(--text-lg)', { lineHeight: 'var(--leading-normal)' }],
//         xl: ['var(--text-xl)', { lineHeight: 'var(--leading-normal)' }],
//         '2xl': ['var(--text-2xl)', { lineHeight: 'var(--leading-tight)' }],
//         '3xl': ['var(--text-3xl)', { lineHeight: 'var(--leading-tight)' }],
//         '4xl': ['var(--text-4xl)', { lineHeight: 'var(--leading-tight)' }],
//         '5xl': ['var(--text-5xl)', { lineHeight: 'var(--leading-tight)' }],
//         '6xl': ['var(--text-6xl)', { lineHeight: 'var(--leading-tight)' }],
//         '7xl': ['var(--text-7xl)', { lineHeight: 'var(--leading-tight)' }],
//         '8xl': ['var(--text-8xl)', { lineHeight: 'var(--leading-tight)' }],
//         '9xl': ['var(--text-9xl)', { lineHeight: 'var(--leading-tight)' }],
//       },
//       fontWeight: {
//         thin: 'var(--font-thin)',
//         extralight: 'var(--font-extralight)',
//         light: 'var(--font-light)',
//         normal: 'var(--font-normal)',
//         medium: 'var(--font-medium)',
//         semibold: 'var(--font-semibold)',
//         bold: 'var(--font-bold)',
//         extrabold: 'var(--font-extrabold)',
//         black: 'var(--font-black)',
//       },
//       lineHeight: {
//         none: 'var(--leading-none)',
//         tight: 'var(--leading-tight)',
//         snug: 'var(--leading-snug)',
//         normal: 'var(--leading-normal)',
//         relaxed: 'var(--leading-relaxed)',
//         loose: 'var(--leading-loose)',
//       },
//       letterSpacing: {
//         tighter: 'var(--tracking-tighter)',
//         tight: 'var(--tracking-tight)',
//         normal: 'var(--tracking-normal)',
//         wide: 'var(--tracking-wide)',
//         wider: 'var(--tracking-wider)',
//         widest: 'var(--tracking-widest)',
//       },
//       spacing: {
//         0: 'var(--space-0)',
//         1: 'var(--space-1)',
//         2: 'var(--space-2)',
//         3: 'var(--space-3)',
//         4: 'var(--space-4)',
//         5: 'var(--space-5)',
//         6: 'var(--space-6)',
//         8: 'var(--space-8)',
//         10: 'var(--space-10)',
//         12: 'var(--space-12)',
//         16: 'var(--space-16)',
//         20: 'var(--space-20)',
//         24: 'var(--space-24)',
//         32: 'var(--space-32)',
//       },
//       borderRadius: {
//         none: 'var(--radius-none)',
//         sm: 'var(--radius-sm)',
//         base: 'var(--radius-base)',
//         md: 'var(--radius-md)',
//         lg: 'var(--radius-lg)',
//         xl: 'var(--radius-xl)',
//         '2xl': 'var(--radius-2xl)',
//         '3xl': 'var(--radius-3xl)',
//         full: 'var(--radius-full)',
//       },
//       boxShadow: {
//         sm: 'var(--shadow-sm)',
//         base: 'var(--shadow-base)',
//         md: 'var(--shadow-md)',
//         lg: 'var(--shadow-lg)',
//         xl: 'var(--shadow-xl)',
//         '2xl': 'var(--shadow-2xl)',
//         inner: 'var(--shadow-inner)',
//       },
//       transitionDuration: {
//         fast: 'var(--transition-fast)',
//         base: 'var(--transition-base)',
//         slow: 'var(--transition-slow)',
//         slower: 'var(--transition-slower)',
//       },
//       zIndex: {
//         dropdown: 'var(--z-dropdown)',
//         sticky: 'var(--z-sticky)',
//         fixed: 'var(--z-fixed)',
//         'modal-backdrop': 'var(--z-modal-backdrop)',
//         modal: 'var(--z-modal)',
//         popover: 'var(--z-popover)',
//         tooltip: 'var(--z-tooltip)',
//         toast: 'var(--z-toast)',
//       },
//       maxWidth: {
//         'container-sm': 'var(--container-sm)',
//         'container-md': 'var(--container-md)',
//         'container-lg': 'var(--container-lg)',
//         'container-xl': 'var(--container-xl)',
//         'container-2xl': 'var(--container-2xl)',
//       },
//     },
//   },
//   plugins: [],
// }
